### ISSUE TITLE
Locating an item with a separate workspace fails to select the item

### ISSUE THREAD

**Issue by alexcpendleton** [alexcpendleton/Pendletron.Vsix.LocateInTFS#12]
Hi everybody.

I have two Workspaces: WS_01 and WS_02.
The active Workspace at SourceControlExplorer ComboBox is WS_01.

If I try to locate an item that belongs to WS_02, it wont find.
It changes to WS_02 but the item is not selected.

I tested both Visual Studio 2012 and 2013.
Am I doing anything wrong?

Thanks,
Wilsade
https://visualstudiogallery.msdn.microsoft.com/5cc44f63-4ea8-4c17-8aa4-95037a2d32ef/view/Discussions

**Comment by jawn** [comment]
Related to #18 

When I perform "locate in TFS" twice then it will select the correct item.
