### ISSUE TITLE
Scroll to selected file

### ISSUE THREAD

**Issue by jawn** [alexcpendleton/Pendletron.Vsix.LocateInTFS#17]
## Steps
In the solution explorer: use "Locate in TFS" on the last file in a directory with many files.

## Expected result
Source control explorer is opened in the corresponding folder.
File is selected.
File is visible (scroll down if neededà

## Actual result
Source control explorer is opened in the corresponding folder: 👍 
File is selected: 👍 
File is not visible since I have to scroll down in the directory with many files: 👎

**Comment by alexcpendleton** [comment]
Could you please tell me what version of Visual Studio you're using, and what version of Windows? Thanks for submitting this issue!

**Comment by jawn** [comment]
Visual Studio 15.6.4
Windows 10
![image](https://user-images.githubusercontent.com/1705112/38018179-742f2614-3274-11e8-855c-3947d84cebd8.png)
