### ISSUE TITLE
Support Visual Studio 2019

### ISSUE THREAD

**Issue by jawn** [alexcpendleton/Pendletron.Vsix.LocateInTFS#19]
Visual Studio 2019 is currently available as RC (release candidate).

This [article](https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/) describes how to modify the .vsixmanifest to add Visual Studio 2019 support.

It seems an easy change in theory, let me know if you prefer a PR.

**Comment by alexcpendleton** [comment]
Thanks for the information! I am working on this but it's not quite that simple to migrate this extension. There are some legacy parts that will take some rewriting. I am trying to work through it, though.

**Comment by alexcpendleton** [comment]
This is now available for 2019 on the VS Marketplace. I'm so grateful for your kind assistance, and thankful for your patience. It did actually work, despite the warning messages for future versions. I'll try to tackle those for next time. Thanks again!
