### ISSUE TITLE
VS2019 depricated API warning

### ISSUE THREAD

**Issue by mdevol** [alexcpendleton/Pendletron.Vsix.LocateInTFS#21]
VS2019 is giving a warning/error about this extension using a deprecated API and is blocking the extension.

**Comment by alexcpendleton** [comment]
Oh no! Could you include a screenshot of the warning/error? Thank you!

**Comment by mdevol** [comment]
The first attached file shows the warning message in VS2019 just below the ribbon bar.  The second attached file shows the detailed information when you click the Manage performance link.  I'm using VS2019 version 16.1.1

________________________________

**Comment by alexcpendleton** [comment]
Github doesn't seem to be attaching the files you sent, I think by e-mail. If possible, could you include them through the issues web UI? https://github.com/alexcpendleton/Pendletron.Vsix.LocateInTFS/issues/21

**Comment by mdevol** [comment]
Here are the attached files.

![VS2019 warning](https://user-images.githubusercontent.com/51177230/58599700-404ace80-8236-11e9-9d84-41974ac4ad8b.png)
![Performance Manager](https://user-images.githubusercontent.com/51177230/58599711-49d43680-8236-11e9-99df-a88bd5fe40a2.png)

**Comment by arobasse2** [comment]
Hello

Since I updated to VS 16.6.2, (from 16.4.1) the extension is no longer visible (any menu item with "Locate in TFS" are not show anymore)
This extension was very usefull, it is sad it not working now.

**Comment by erezwanderman** [comment]
The notification is still showing. It links here: https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/
