### ISSUE TITLE
Support Visual Studio 2022

### ISSUE THREAD

**Issue by kamszyc** [alexcpendleton/Pendletron.Vsix.LocateInTFS#23]
Stable version of Visual Studio 2022 was released on 8th of November.
Do you have plans to update the extension to support new VS version?

Unfortunately, due to migration to 64 bits, it seems to not be easy
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by alexcpendleton** [comment]
I do not have plans to update the extension. It may happen, but I wouldn't expect it soon.

**Comment by rongjun0926** [comment]
@mgottvaId great

**Comment by sonerfromnurland** [comment]
@mgottvaI @alexcpendleton  great behavior thanks.

**Comment by alexcpendleton** [comment]
I have other things I have to do with my life, this is not in my list of priorities. Sorry. You have everything you need to carry this on if it is something valuable to you. Be well.
